### ISSUE TITLE
How can I train a 'pre-trained' model on my own datasets? 

### ISSUE THREAD

**Issue by A1ita99** [jjhuangcs/AdvINN#1]
Congratulations on your great work! It seems that your code in 'train.py' optimizes the weights of the pre-trained model for each image. I wonder how I can train a 'pre-trained' model on my own datasets first?

**Comment by Brittany-Chen** [comment]
The  weights of the pre-trained model is optimized from random initializtation for 1000 iterations with batch size 10.

**Comment by Brittany-Chen** [comment]
@A1ita99 The  weights of the pre-trained model is optimized from random initializtation for 1000 iterations with batch size 10.

**Comment by A1ita99** [comment]
> @A1ita99 The weights of the pre-trained model is optimized from random initializtation for 1000 iterations with batch size 10.

Thanks for your reply!
